[project]
name = "ready-rudi"
version = "0.1.0"
description = "Assessment tool for clients"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.25.0",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "plotly>=5.14.0",
    "sqlalchemy>=2.0.0"
]
